In [7]:
import numpy as np

### 1-D

In [95]:
import math

np.random.seed(42)

a = np.random.rand(5)


def online_softmax(x):
    prev_max = float("-inf")
    curr_max = float("-inf")
    curr_exp_sum = 0.0
    for elem in x:
        prev_max = curr_max
        curr_max = max(curr_max, elem)
        curr_exp_sum = curr_exp_sum * math.exp(prev_max - curr_max) + math.exp(elem - curr_max)

    return np.exp(x - curr_max) / curr_exp_sum


np.allclose(online_softmax(a), np.exp(a) / np.sum(np.exp(a)))

True

### Multi-Dimensions

In [46]:
np.random.seed(42)

a = np.random.randn(2, 5)
a

array([[ 0.49671415, -0.1382643 ,  0.64768854,  1.52302986, -0.23415337],
       [-0.23413696,  1.57921282,  0.76743473, -0.46947439,  0.54256004]])

In [63]:
np.exp(a) / np.sum(np.exp(a), axis=-1, keepdims=True)

array([[0.16763982, 0.08884021, 0.19495956, 0.46784333, 0.08071708],
       [0.07801474, 0.47830449, 0.21239961, 0.06165537, 0.16962579]])

In [64]:
np.exp(a - np.max(a, axis=-1, keepdims=True)) / np.sum(
    np.exp(a - np.max(a, axis=-1, keepdims=True)), axis=-1, keepdims=True
)

array([[0.16763982, 0.08884021, 0.19495956, 0.46784333, 0.08071708],
       [0.07801474, 0.47830449, 0.21239961, 0.06165537, 0.16962579]])

In [51]:
import torch
import torch.nn.functional as F

F.softmax(torch.tensor(a), dim=-1)
# np.allclose(online_softmax(a), F.softmax(torch.tensor(a), dim=-1).numpy())

tensor([[0.1676, 0.0888, 0.1950, 0.4678, 0.0807],
        [0.0780, 0.4783, 0.2124, 0.0617, 0.1696]], dtype=torch.float64)